### ISSUE TITLE
railsgirls 风格调整

### ISSUE THREAD

**Issue by windy** [railsgirls-cn/campo#1]
目前已经布署上线, 直接访问 http://railsgirlschina.com 查看.

随时可回滚至原有风格

**Comment by sundevilyang** [comment]
感觉红色的Nav 和绿色的按钮不搭配。   

我建议先不用那么着急设计样式和风格， 先完善一下页面内容。网站的样式设计可以找参加过我们活动的女孩帮忙，北京就有好几个愿意帮忙。但是我们要先把内容和网站的功能大体设计一下。你们说呢？
@windy @harryworld

**Comment by windy** [comment]
@sundevilyang 我的意思是先做了简单的样式, 符合社区文化, 随后再继续调整.

接下来就可以讨论一些功能

**Comment by sundevilyang** [comment]
好，那就用红色的试一试。看看大家是否会吐槽。

**Comment by windy** [comment]
基调为红色, 暂时关闭这个 issues.
