### ISSUE TITLE
字段修订讨论

### ISSUE THREAD

**Issue by windy** [railsgirls-cn/campo#2]
讓用戶填寫以下資料
1. 教練／學員／Helper／贊助商
2. 參與過那個地方的RailsGirls
3. 當時教練是誰？

**Comment by sundevilyang** [comment]
1、 如果一个人有多重身份呢？  例如李路，他既是赞助商、又是教练。 可不可以是多选的，打钩的那种？
2、这个可以有。 但是至于我们先前的这些女孩子，感觉她们已经没有很多的驱动力来注册我们的网站了，至少在我们RailsGirls成为很有影响力的活动之前是这样的。这几天我在先前北京的几个RG活动群里面宣传了好几遍，大家积极性不是很高。
3、可以有。

**Comment by windy** [comment]
你可以访问 /admin 直接到后台, 管理一下分类吧, 我只是简单做了几个, 你也可删掉或者调整.
